package it.eliapitozzi.medicalmaterialant.model;

/**
 * @author Elia
 */
public enum Material {
    LETTINO,
    LETTO_ELETTRICO,
    MATERASSINO,
    COMODA,
    PIANTANA,
    CARROZZINA_A_ROTELLE,
    CIAMBELLA,
    DEAMBULATORE,
    SOLLEVATORE_ELETTRICO,
    ALZACOPERTA,
    ALZAPERSONE_DA_PAVIMENTO,
    CAPRETTA,
    BASTONE,
    ALZAWATER,
    SEGGIOLINO_DA_VASCA,
    PADELLA,
    CUSCINO_IN_SILICONE,
    ALZAWATER_DA_APPOGGIO,
    PAPPAGALLO,
    ASPIRATORE
}
